
function [Hx] = longfield(a,b,X,Y,I)
    %a is half of stripline length in nanometers
    %b is half of stripline height in nanometers
    %X is relative x position (centred at 0,0 on the stripline)
    %Y is relative Y position (centred at 0,0 on the stripline)
    %I is current value in amps
    %Returns longitudinal magnetic field component Hx


    p=pi;
    Hx = (-I/(8*p*a*b))* ...
        ((a-X)* ...
        (((1/2)*log(((b-Y)^2 + (a-X)^2)/((-b-Y)^2+(a-X)^2))) ...
        + ((b-Y)/(a-X))*atan((a-X)/(b-Y)) ...
        -((-b-Y)/(a-X))*atan((a-X)/(-b-Y))) ...
        -(-a-X)* ... %potentially +
        ((1/2)*log(((b-Y)^2 + (-a-X)^2)/((-a-X)^2+(-b-Y)^2)) ...
        + ((b-Y)/(-a-X))*atan((-a-X)/(b-Y)) ...
        -((-b-Y)/(-a-X))*atan((-a-X)/(-b-Y))));
end
